<Project>

  <PropertyGroup>
    <Authors>WayaQuick</Authors>
    <Company>WayaQuick</Company>
    <Copyright>© 2026 WayaQuick</Copyright>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/WAYA-MULTI-LINK/WAYA-PAY-CHAT-2.0-.NET-LIBRARY</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
  </PropertyGroup>

</Project>
