<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <PackageId>Wayapay</PackageId>
    <Version>1.0.0</Version>
    <Authors>Emmanuel Mustapha</Authors>
    <Company>Wayaquick</Company>
    <Description>Official .NET SDK for the WayaPay payment gateway</Description>
    <PackageTags>wayapay;payment;nigeria;fintech;sdk</PackageTags>
    <PackageProjectUrl>https://github.com/WAYA-MULTI-LINK/WAYA-PAY-CHAT-2.0-.NET-LIBRARY</PackageProjectUrl>
    <RepositoryUrl>https://github.com/WAYA-MULTI-LINK/WAYA-PAY-CHAT-2.0-.NET-LIBRARY</RepositoryUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>
</Project>